### ISSUE TITLE
Boost IPC core dumped

### ISSUE THREAD

**Issue by atweiden** [libbitcoin/libbitcoin-node#36]
With the [libbitcoin-node 2.0.0 release](https://github.com/atweiden/pkgbuilds/blob/master/libbitcoin-node/PKGBUILD), running `bitcoin_node` throws an exception:

```
$ bitcoin_node --help
1431388742 INFO [blockchain]: Mapping: "blockchain/blocks_lookup"
1431388742 FATAL [blockchain]: The file failed to map: "blockchain/blocks_lookup" error: 2
1431388742 INFO [blockchain]: Mapping: "blockchain/blocks_rows"
1431388742 FATAL [blockchain]: The file failed to map: "blockchain/blocks_rows" error: 2
1431388742 INFO [blockchain]: Mapping: "blockchain/spends"
1431388742 FATAL [blockchain]: The file failed to map: "blockchain/spends" error: 2
1431388742 INFO [blockchain]: Mapping: "blockchain/txs"
1431388742 FATAL [blockchain]: The file failed to map: "blockchain/txs" error: 2
1431388742 INFO [blockchain]: Mapping: "blockchain/history_lookup"
1431388742 FATAL [blockchain]: The file failed to map: "blockchain/history_lookup" error: 2
1431388742 INFO [blockchain]: Mapping: "blockchain/history_rows"
1431388742 FATAL [blockchain]: The file failed to map: "blockchain/history_rows" error: 2
1431388742 INFO [blockchain]: Mapping: "blockchain/stealth_index"
1431388742 FATAL [blockchain]: The file failed to map: "blockchain/stealth_index" error: 2
1431388742 INFO [blockchain]: Mapping: "blockchain/stealth_rows"
1431388742 FATAL [blockchain]: The file failed to map: "blockchain/stealth_rows" error: 2
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  No such file or directory
Aborted (core dumped)
```

on boost 1.5.8 (archlinux x86_64)

**Comment by evoskuil** [comment]
Thanks, I'll take a look.

I should make a note that indicates the node console is just a demo app. It's slated to become a robust node, but it currently has none of the config/args that server has and hasn't been tested. There's no `--help` option.

The `libbitcoin-node` library on the other hand is a core part of `libbitcoin-server`. If you want to run a full node you can run server. There is a configuration option to disable the ZMQ protocol as well.

**Comment by evoskuil** [comment]
It looks like this is just a case of the console/demo app requiring more manual configuration. See comment:

https://github.com/libbitcoin/libbitcoin-node/blob/master/console/main.cpp#L316-L317

**Comment by evoskuil** [comment]
Note that the console app is a full-fledged node in version3.
