### ISSUE TITLE
Error at Block 32258 (mainnet) With difficult=false

### ISSUE THREAD

**Issue by JasonCoombs** [libbitcoin/libbitcoin-node#380]
(solved by enabling difficult = true but that's not the problem being reported by this issue)

This is presumably expected behavior, but is there a reason that we allow difficult=false on mainnet at all if it's impossible to process block 32258 and is there any documentation as to why this block but not others causes a problem when difficult = false? Shouldn't difficult=false mode cause us to ignore the bits field entirely? We don't care whether the block contains proof of work, and we shouldn't care whether the difficulty claimed for the block matches the expected value, if difficulty is disabled.

https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers

4 | bits | uint32_t | The calculated difficulty target being used for this block

See also:

https://www.blockchain.com/btc/block-index/47108/000000006e35246abda2e8f2ab945780ea7619c74a3ee5db5ca6ff0f4d5b88c6

error 32: proof of work does not match bits field

**Comment by evoskuil** [comment]
It’s a hard fork. Your peers are on a different chain. Perfectly correct behavior.

**Comment by JasonCoombs** [comment]
Which hard fork? I've been searching for details. Haven't found any information suggesting there was a hard fork at block 32,257 -- was there a BIP for this?

https://github.com/bitcoin/bips

https://en.wikipedia.org/wiki/List_of_bitcoin_forks
https://en.bitcoin.it/wiki/Softfork
https://en.bitcoin.it/wiki/Protocol_documentation

**Comment by evoskuil** [comment]
We treat testnet as a hard fork from Bitcoin rules.

**Comment by JasonCoombs** [comment]
Got it. Thanks. Do you have any additional details for historic purposes that should go in the docs?

This looks like it explains the history of the testnet adequately:

https://en.bitcoinwiki.org/wiki/Testnet

**Comment by evoskuil** [comment]
No, just our testnet config, along with regrets is documented on the server wiki.

**Comment by JasonCoombs** [comment]
Do you mean this? It looks like this part of the wiki needs to be updated. Can we configure the GitHub repositories to permit public edits of the wiki pages, or use the technique that other projects use where the wiki is its own repository which can receive pull requests and feeds in to the official wiki?

https://github.com/libbitcoin/libbitcoin-server/wiki/Fork-Settings

**Comment by evoskuil** [comment]
It’s current for production (version3).
