### ISSUE TITLE
Testnet Error Validating Block 872730

### ISSUE THREAD

**Issue by JasonCoombs** [libbitcoin/libbitcoin-node#381]
Trying to debug this error condition on testnet (extra debug logging added) -- is this a known issue?

Does it look like the block organizer is failing on block 872,729 or is handle_accept being called on those three parallel threads (thread ids 0x700006a9c000, 0x700006996000, 0x700006913000) to process the three newly-received blocks (875420, 872743, 875370) and is the first attempt by header_organizer to handle_accept() which encounters error bitcoin:5 missing block parent causing the "store is now corrupt" condition? Adding thread id to each debug log message has been helping me trace program flow and figure out which thread is responsible, but I haven't added thread id here yet and wonder if there is any existing knowledge about this particular testnet error condition or block.

```
16:18:03.892302 INFO [node] Block #872729 (00) [0000000000000a17e01273a1399d3bcf53f1dbbe2a799b43d4a46538b8ae97a2] 000.000 00.00% 121
16:18:03.915318 INFO [node] Block #875420 (06) [000000005c3af6b0824371cd205372c256317474dbf91a1c4c71eb0bb7e912ba] 000.006 00.49% 121
16:18:03.948691 INFO [blockchain] Organized blocks [872729-872729]
16:18:04.066179 INFO [node] Block #872743 (00) [00000000ea2c44c2dc5eab6dbe0b998642766ed1292ae96ce51f28e7e24de279] 000.000 00.00% 120
16:18:04.560409 FATAL [blockchain] Failure in block organization, store is now corrupt: operation failed
16:18:04.560472 FATAL [blockchain] 0x700006a9c000 error header_organizer::handle_accept()  error_code = bitcoin:5 missing block parent
16:18:04.560840 INFO [node] Block #875370 (03) [000000000501702a60f618058d25bf22f6f1fac4d185b4b5cd862aebe24e718f] 000.000 00.00% 119
16:18:04.560946 FATAL [blockchain] 0x700006996000 error header_organizer::handle_accept()  error_code = bitcoin:5 missing block parent
16:18:04.641315 FATAL [blockchain] 0x700006913000 error header_organizer::handle_accept()  error_code = bitcoin:5 missing block parent
16:18:04.801483 ERROR [node] Internal failure generating block locator for [35.192.190.35:18333] object does not exist
16:18:04.804414 INFO [node] Block #875380 (03) [0000000030e7c4d94f0cc964730e71708a9de8f8101db0ab36687ce8584c200f] 000.000 00.00% 117
16:18:04.805649 INFO [node] Block #875389 (03) [000000001ddd92315e9207598b4b3449bb0064026c4f60e3a3eb4431a6664388] 000.021 00.10% 116
16:18:04.805857 INFO [node] Block #875398 (03) [0000000033cc256e719433a6f3292c4bda80a84b0cb4f87aaae8b3714b2481fc] 000.028 00.11% 115
16:18:04.805990 INFO [node] Block #875407 (03) [000000000fde7a6c22c119647583eadea4e43305d88f0a115c4b24600f8c8c1b] 000.035 00.12% 114
16:18:04.809475 ERROR [node] Internal failure generating block locator for [145.239.6.138:18333] object does not exist
16:18:04.815718 ERROR [node] Internal failure generating block locator for [58.35.77.155:18333] object does not exist
16:18:04.933441 INFO [node] Block #875416 (03) [0000000026488fc37fb963e3ece0f02d6d4f58e18cfc46d32f77ac0a64121b91] 000.000 00.00% 113
16:18:05.071772 INFO [node] Block #872758 (00) [000000008bd1c23a25d1e01c634764735eec76111ea4ba414533976197c7e023] 000.000 00.00% 113
16:18:06.099880 INFO [network] Connected outbound channel [68.168.122.2:18333] (1)
16:18:06.099981 ERROR [node] Internal failure generating block locator for [68.168.122.2:18333] object does not exist
```

**Comment by evoskuil** [comment]
If the parent is missing during validation it is not a known issue.

**Comment by JasonCoombs** [comment]
After adding additional debug logging, it is clear that the following header hash is not found:

`00000000470b9e0dd4f6fb72c93e0c655f68069899a5b2a0b4e413ef8006469a`

This is the umkoin genesis block.

http://blockexplorer.umkoin.org/en/blockexplorer.php?net=mainnet&block=0

**Comment by JasonCoombs** [comment]
Also seeing Orphan header errors from the blocks supplied by the same peer, and of course they are the umkoin blockchain blocks. e.g.

http://blockexplorer.umkoin.org/en/blockexplorer.php?net=mainnet&block=0000000053d3d3b583afbe4751ca900a4facdfbe4c12f03c1a96d17889e84b3e

as an immediate work-around for my other debugging work I'm just going to blacklist the peer: 62.182.124.202

but we will need an improvement to bad peer handling. what do you recommend?

**Comment by JasonCoombs** [comment]
Here's another umkoin node, and note how we presume its blocks to be a potential chain fork:

19:40:36.400769 DEBUG [node] 0x70000efd3000 protocol_header_in::handle_store_header() Orphan header [0000000053d3d3b583afbe4751ca900a4facdfbe4c12f03c1a96d17889e84b3e] from [82.193.103.110:6333] missing block parent
19:40:36.400915 DEBUG [node] Ask [82.193.103.110:6333] for headers from [0000000000000421a264b2a6b2535d5cd0e628f16ddf86f27f5fb34eb3667a7e] through [0000000053d3d3b583afbe4751ca900a4facdfbe4c12f03c1a96d17889e84b3e]

**Comment by JasonCoombs** [comment]
Is this a different error at block height 872730 ?? Immediately after 872729 was organized, this:

```
23:04:18.738879 INFO [blockchain] 0x700004774000 Organized blocks [872729-872729]
23:04:18.739733 DEBUG [blockchain] 0x700004774000 Got next block #872730
23:04:18.744248 DEBUG [blockchain] Verify failed [872730] : invalid witness
 libconsensus : false
 forks        : 16382
 outpoint     : 1b9e1323923508ecc3d097f11aeaa66acbe6a6d3c4ea6b25d57d34ee9c8d660d:0
 script       : a914e5a679f81579cbf20bb2a4764be9e95e8b3e396787
 value        : 100000000
 inpoint      : 118c83b2c7aa4b500e0c0333dbfef990ca6c324004d68f68acb10ddada918474:0
 transaction  : 01000000020d668d9cee347dd5256beac4d3a6e6cb6aa6ea1af197d0c3ec08359223139e1b00000000171600143f0402fcb8beef28a89be7e94794ec66d469fdb6feffffff0d668d9cee347dd5256beac4d3a6e6cb6aa6ea1af197d0c3ec08359223139e1b010000006b483045022100eaceee00202693d7d54aa84bd8b216f62b1f041b16e08e0352eb1ed50f1ef10102201a90288f667f975cc8d524431d61bd8b15f5d189610d31a9bd12ee37c0674f06012103c4561ce27291b1730e5a429934f45fb4ff9b56e24b6e10e0d176f198fa029671feffffff02506c9800000000001976a9140af575373dad17150d91b6a191a371b59e09d87f88ac001c4e0e0000000017a91403572c975aec5228c0e2982ef8a03b6830e0554f8719510d00
23:04:19.687191 DEBUG [node] Maximal (1) not found.
```

**Comment by JasonCoombs** [comment]
This invalid witness error was probably the original cause of the error encountered three days ago.

https://github.com/libbitcoin/libbitcoin-node/issues/381#issue-364669705

That log excerpt was from the console output not from the debug log file.

**Comment by JasonCoombs** [comment]
This looks relevant: https://bitcointalk.org/index.php?topic=2052851.0

**Comment by JasonCoombs** [comment]
This is how bx 3.4.0 decodes the tx:

```
$ bx tx-decode 01000000020d668d9cee347dd5256beac4d3a6e6cb6aa6ea1af197d0c3ec08359223139e1b00000000171600143f0402fcb8beef28a89be7e94794ec66d469fdb6feffffff0d668d9cee347dd5256beac4d3a6e6cb6aa6ea1af197d0c3ec08359223139e1b010000006b483045022100eaceee00202693d7d54aa84bd8b216f62b1f041b16e08e0352eb1ed50f1ef10102201a90288f667f975cc8d524431d61bd8b15f5d189610d31a9bd12ee37c0674f06012103c4561ce27291b1730e5a429934f45fb4ff9b56e24b6e10e0d176f198fa029671feffffff02506c9800000000001976a9140af575373dad17150d91b6a191a371b59e09d87f88ac001c4e0e0000000017a91403572c975aec5228c0e2982ef8a03b6830e0554f8719510d00
transaction
{
    hash 118c83b2c7aa4b500e0c0333dbfef990ca6c324004d68f68acb10ddada918474
    inputs
    {
        input
        {
            address_hash e5a679f81579cbf20bb2a4764be9e95e8b3e3967
            previous_output
            {
                hash 1b9e1323923508ecc3d097f11aeaa66acbe6a6d3c4ea6b25d57d34ee9c8d660d
                index 0
            }
            script [00143f0402fcb8beef28a89be7e94794ec66d469fdb6]
            sequence 4294967294
        }
        input
        {
            address_hash e95f772e516a0bb68141e845483e23bc28acd29b
            previous_output
            {
                hash 1b9e1323923508ecc3d097f11aeaa66acbe6a6d3c4ea6b25d57d34ee9c8d660d
                index 1
            }
            script "[3045022100eaceee00202693d7d54aa84bd8b216f62b1f041b16e08e0352eb1ed50f1ef10102201a90288f667f975cc8d524431d61bd8b15f5d189610d31a9bd12ee37c0674f0601] [03c4561ce27291b1730e5a429934f45fb4ff9b56e24b6e10e0d176f198fa029671]"
            sequence 4294967294
        }
    }
    lock_time 872729
    outputs
    {
        output
        {
            address_hash 0af575373dad17150d91b6a191a371b59e09d87f
            script "dup hash160 [0af575373dad17150d91b6a191a371b59e09d87f] equalverify checksig"
            value 9989200
        }
        output
        {
            address_hash 03572c975aec5228c0e2982ef8a03b6830e0554f
            script "hash160 [03572c975aec5228c0e2982ef8a03b6830e0554f] equal"
            value 240000000
        }
    }
    version 1
}
```

**Comment by evoskuil** [comment]
Please explain why you think the implementing is invalid.

**Comment by evoskuil** [comment]
A missing parent is not presumed to be a chain fork. It only implies we are missing one or more intervening blocks, on the strong chain or otherwise.

**Comment by JasonCoombs** [comment]
Did you read the bitcointalk discussion about this block and its transaction 44? Ordinarily there is at least one witness, but in this case it appears to be valid for witness length to be zero.

As a result of the invalid_witness error the correct block is never validated, which causes every subsequent block to produce a missing parent condition. This condition will never end, libbitcoin will never be able to validate another block, because we don't consider the correct block to be valid.

**Comment by JasonCoombs** [comment]
https://github.com/libbitcoin/libbitcoin-node/issues/381#issuecomment-425668397

My point, above, about umkoin's errant nodes and the blocks being offered, accepted, and validated except for the missing parent error, is that in this case a missing parent should not be considered expected and normal. Do we really want libbitcoin to store the entire umkoin blockchain and every block of every other BTC fork that doesn't bother to differentiate its novel chain in some way? Accepting and storing umkoin blocks, waiting to some day receive their parents and do a chain reorg for BTC, should not be a thing.

http://www.umkoin.org/en/faq.php#who-created-umkoin

**Comment by thecodefactory** [comment]
>  This condition will never end, libbitcoin will never be able to validate another block, because we don't consider the correct block to be valid.

Just noting that version3 is production, and the community servers are all current.

**Comment by JasonCoombs** [comment]
> Just noting that version3 is production, and the community servers are all current.

Testnet? Based on my testing and code review of version 3 it doesn't appear possible for it to be used with the Testnet unless somebody modifies this line of code and recompiles for the Testnet context:

https://github.com/libbitcoin/libbitcoin-node/blob/version3/console/main.cpp#L38

**Comment by JasonCoombs** [comment]
Thanks for that link. Had never seen the list of Community Servers before. I'll set up a version3 Testnet node right now and try to figure out what the difference is with how block 872730 was being validated.

**Comment by thecodefactory** [comment]
> Thanks for that link. Had never seen the list of Community Servers before. I'll set up a version3 Testnet node right now and try to figure out what the difference is with how block 872730 was being validated.

No problem.  And no need for a rebuild.  It's all configuration file based, just go through it and look for testnet options/values.

**Comment by JasonCoombs** [comment]
Something must have changed in v4 if there was a way to configure v3 for Testnet based only on the config files. The hard-coded mainnet context here causes --initchain to write the mainnet genesis block regardless of config file settings:

https://github.com/libbitcoin/libbitcoin-node/blob/version3/console/main.cpp#L38

**Comment by evoskuil** [comment]
Lots has changed in v4 ;). Se my previous comments on configuring the genesis block.

**Comment by JasonCoombs** [comment]
Which comment? I've followed all the instructions that I've been able to find suggesting that config files alone are able to determine which genesis block gets used with --initchain but have never been able to get v4 to write the correct testnet genesis block.

**Comment by JasonCoombs** [comment]
version3 on Testnet is now running. as advertised, all that was needed to activate Testnet context was to edit the bn.cfg config file. after days of trying to figure out why v4 would not write the Testnet genesis block I finally ripped out almost all use of the config file and now I have command line parameters and built-in defaults that can optionally be overridden by config file settings instead.

**Comment by evoskuil** [comment]
This issue seems to have gone way off topic. Can you please clarify what is the problem you are seeing and if you have another problem create an independent issue.

As I’ve pointed out WRT config in v4, the genesis block is configurable. If that is not working you should create an issue and/or pull request to resolve it. Replacing config altogether bevause you cannot find the source of the issue is not ideal.

**Comment by JasonCoombs** [comment]
This issue is the apparent validation failure with block 872730 on Testnet with v4.

I'll have more details to offer after comparing with v3. Has nobody else configured v4 with Testnet and synchronized to the current block? Are there no Community Servers running v4 yet?

**Comment by JasonCoombs** [comment]
> Replacing config altogether bevause you cannot find the source of the issue is not ideal.

It didn't seem worth the additional time to debug the config file mechanism when there was not yet a way to add command line parameters to override both hard-coded defaults and the config file, and when there weren't enough hard-coded defaults to operate a node without a config file at all. If nobody else gets around to finding and solving the problem writing the Testnet genesis block when --initchain is done then I'll eventually submit a PR proposing my fully-revised code which adds a second step in the config process, makes it easier to add new command-line parameters, and adds missing defaults.

**Comment by evoskuil** [comment]
Master is staging for v4, sync/validation is a work in progress. It is not fully functional yet. Segwit is complete in both v3 and v4. I see no problem with it based on your comments.

**Comment by JasonCoombs** [comment]
If you have a moment perhaps you could use your substantially-faster SSD-based equipment and try to sync to current with v4 on Testnet. I think you'll encounter the same validation failure that I have on Mac OS with my mechanical hard drive-based slow sync. It takes a whole day just to get to the next debugging step. Twice my intent was to stop the sync and make a backup copy of the database before it reached block 872730 so that I could restore from backup at a valid state before the error occurs, and twice I have fallen asleep and missed it. :-)

**Comment by evoskuil** [comment]
It is not an objective to move all config options to the command line. The node operates without a config file. If you have a problem with config then you should address the problem, not simply replace the implementation that you don’t yet understand well enough to fix. If you are proposing a significant design change you should probably discuss it on slack. These two things seem to have become conflated.

**Comment by evoskuil** [comment]
This issue has become an open-ended discussion of whatever you are encountering. That is not the purpose of these items. General discussion should be moved to slack. Please create independent issues for independent problems (e.g. validation failure, store corruption, genesis config) and try to keep the issue focused on the problem.

**Comment by thecodefactory** [comment]
@JasonCoombs If you do not enter a testnet genesis block, mainnet will be written.  Can you confirm that you've edited the config file in the right spots?

https://github.com/libbitcoin/libbitcoin-server/blob/master/data/bs.cfg#L252

Also, v4 is not expected to work as @evoskuil has mentioned a couple times, so your mileage may vary.

I do think this issue has become very confusing, so perhaps I missed that you've done that already.

**Comment by JasonCoombs** [comment]
Thanks for that. The bn.cfg file doesn't have a genesis_block setting and I haven't been using bs yet.

https://github.com/libbitcoin/libbitcoin-node/blob/master/data/bn.cfg

If the requirement for configuring bn or bs for Testnet mode is to supply the genesis block in the config file that's fine but we should include that in the published instructions.

**Comment by thecodefactory** [comment]
> If the requirement for configuring bn or bs for Testnet mode is to supply the genesis block in the config file that's fine but we should include that in the published instructions.

v4 has a lot of undocumented features since we're literally in the process of making these kinds of updates and haven't gotten to that yet.  That's what it means to not be ready :-)

**Comment by JasonCoombs** [comment]
When I configured v3 for Testnet a few hours ago there was no need for me to supply genesis_block and since it's already hard-coded in the v4 settings.cpp that requirement is probably historical.

https://github.com/libbitcoin/libbitcoin/blob/master/src/settings.cpp#L118

**Comment by JasonCoombs** [comment]
I'm a little confused as to why "it's not ready yet" is an answer that closes an open debugging issue. Trying to fit in correctly with the development process here, maybe this Issue should have included a tag for DEVELOPMENT? My intent is to fix the problem myself, not report a bug and wait for somebody else to do the work.

**Comment by evoskuil** [comment]
This has become unworkable as an issue, it’s basically streaming debugging across at least three issues.

**Comment by thecodefactory** [comment]
> I'm a little confused as to why "it's not ready yet" is an answer that closes an open debugging issue. 

This issue isn't reproducible here.  With a testnet configuration, I was able to sync past the reported failure height without issue.

**Comment by JasonCoombs** [comment]
> This issue isn't reproducible here.

You're using v4 from the master branch and sync'ed to current successfully? I'm using Mac OS, are you on Windows or Linux? Thanks for attempting to reproduce the error condition.

**Comment by JasonCoombs** [comment]
I completed the re-test of a straight git clone of v4 (master branch) and again confirmed that the Mainnet genesis block is being written to the table instead of the Testnet genesis block. The following Issue documents the current result of this test -- can you please explain what you did differently to get Testnet to sync with the development branch and the new v4 code? Thanks.

https://github.com/libbitcoin/libbitcoin-node/issues/382

**Comment by JasonCoombs** [comment]
Examining the processing of block 872730 in v3, compared to v4, and reading again bip141:

https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#Transaction_ID

**"A non-witness program (defined hereinafter) txin MUST be associated with an empty witness field, represented by a 0x00"**

in v3 there is, somehow, a non-empty witness field:

```
01:07:04.817855 VERBOSE [system] 0x70000106c000 script::verify() for prevout_script = dup hash160 [95c78a968018fdedbf6815d62d11648a3db5d46a] equalverify checksig and input_script = [3045022100d8060726e7b91cb4495ea5a8c4bf6e30d92d8816c3d7465fdb27ca1f268417f202205f6793c0193ded4113c6488ddfcd34557a632f6b6f9ab1462d8ef04be68b86d901] [02ad320a9570f170f43678a73b7fd8eb7430d493b26737461c5f90691060599981]
01:07:04.817968 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness forks: 1073758207
01:07:04.817978 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness bien
01:07:04.817984 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness biwi is false
01:07:04.817992 VERBOSE [system] 0x70000106c000 script::verify() for prevout_script = hash160 [e5a679f81579cbf20bb2a4764be9e95e8b3e3967] equal and input_script = [00143f0402fcb8beef28a89be7e94794ec66d469fdb6]
01:07:04.818013 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness forks: 1073758207
01:07:04.818020 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness bien
01:07:04.818027 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness biwi is false
01:07:04.818033 VERBOSE [system] 0x70000106c000 script::verify() is_pay_to_script_hash()
01:07:04.818040 VERBOSE [system] 0x70000106c000 script::verify() embedded_script = zero [3f0402fcb8beef28a89be7e94794ec66d469fdb6]
01:07:04.818053 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness forks: 1073758207
01:07:04.818060 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness bien
01:07:04.818066 VERBOSE [system] 0x70000106c000 script::is_pay_to_witness biwi
01:07:04.818073 VERBOSE [system] 0x70000106c000 script::verify() witnessed embedded_script
01:07:04.818079 VERBOSE [system] 0x70000106c000 script::verify() embedded_script = zero [3f0402fcb8beef28a89be7e94794ec66d469fdb6]
01:07:04.818089 VERBOSE [system] 0x70000106c000 script::verify() input_script = [00143f0402fcb8beef28a89be7e94794ec66d469fdb6]
01:07:04.818100 VERBOSE [system] 0x70000106c000 script::verify() input_witness = [3045022100913d331b78a2c1a2ec0e2af7a826181f26e15e0195cef13f492d2e22b8dd9e2c02201f808621f9684574cbbd755933509f6bce7536aa5c36dd4c57fd635e5485404901] [03e2728bdc007032f5b30c823f4a3cd9236eab5e3a6f23c6ae6be8bd63ff847922]
01:07:04.867900 VERBOSE [system] 0x70000106c000 witness::extract_embedded_script() called
01:07:04.867933 VERBOSE [system] 0x70000106c000 stack_ = [3045022100913d331b78a2c1a2ec0e2af7a826181f26e15e0195cef13f492d2e22b8dd9e2c02201f808621f9684574cbbd755933509f6bce7536aa5c36dd4c57fd635e5485404901] [03e2728bdc007032f5b30c823f4a3cd9236eab5e3a6f23c6ae6be8bd63ff847922]
01:07:04.867961 VERBOSE [system] 0x70000106c000 witness::extract_embedded_script() out_stack.size == 2 && is_push_size(out_stack)
01:07:04.867998 VERBOSE [system] 0x70000106c000 witness::verify() called extract_embedded_script() and returned true
...
01:07:04.873117 DEBUG [node] Connected block [0000000000000521adc862e31310e79d7f98455933833ba2c95d5e4b257a6aef] at height [872730] from [206.189.169.240:18333] (1073758207, 4).
```

while in v4 we have:

```
07:47:45.167120 VERBOSE [system] 0x700007887000 script::verify() for prevout_script = dup hash160 [95c78a968018fdedbf6815d62d11648a3db5d46a] equalverify checksig
07:47:45.167131 VERBOSE [system] 0x700007887000 and in.script() = [3045022100d8060726e7b91cb4495ea5a8c4bf6e30d92d8816c3d7465fdb27ca1f268417f202205f6793c0193ded4113c6488ddfcd34557a632f6b6f9ab1462d8ef04be68b86d901] [02ad320a9570f170f43678a73b7fd8eb7430d493b26737461c5f90691060599981]
07:47:45.167242 VERBOSE [system] 0x700007887000 script::is_pay_to_witness forks: 16382
07:47:45.167251 VERBOSE [system] 0x700007887000 script::is_pay_to_witness bien
07:47:45.167258 VERBOSE [system] 0x700007887000 script::is_pay_to_witness biwi is false
07:47:45.167271 VERBOSE [system] 0x700007887000 script::verify() for prevout_script = hash160 [e5a679f81579cbf20bb2a4764be9e95e8b3e3967] equal
07:47:45.167283 VERBOSE [system] 0x700007887000 and in.script() = [00143f0402fcb8beef28a89be7e94794ec66d469fdb6]
07:47:45.167300 VERBOSE [system] 0x700007887000 script::is_pay_to_witness forks: 16382
07:47:45.167307 VERBOSE [system] 0x700007887000 script::is_pay_to_witness bien
07:47:45.167313 VERBOSE [system] 0x700007887000 script::is_pay_to_witness biwi is false
07:47:45.167319 VERBOSE [system] 0x700007887000 script::verify() is_pay_to_script_hash()
07:47:45.167326 VERBOSE [system] 0x700007887000 script::verify() embedded_script = zero [3f0402fcb8beef28a89be7e94794ec66d469fdb6]
07:47:45.167343 VERBOSE [system] 0x700007887000 script::is_pay_to_witness forks: 16382
07:47:45.167350 VERBOSE [system] 0x700007887000 script::is_pay_to_witness bien
07:47:45.167356 VERBOSE [system] 0x700007887000 script::is_pay_to_witness biwi
07:47:45.167362 VERBOSE [system] 0x700007887000 script::verify() witnessed embedded_script
07:47:45.167368 VERBOSE [system] 0x700007887000 script::verify() embedded_script = zero [3f0402fcb8beef28a89be7e94794ec66d469fdb6]
07:47:45.167379 VERBOSE [system] 0x700007887000 script::verify() in.script() = [00143f0402fcb8beef28a89be7e94794ec66d469fdb6]
07:47:45.167390 VERBOSE [system] 0x700007887000 script::verify() input_witness =
07:47:45.167397 VERBOSE [system] 0x700007887000 witness::extract_embedded_script() called
07:47:45.167404 VERBOSE [system] 0x700007887000 stack_ =
07:47:45.167410 VERBOSE [system] 0x700007887000 witness::extract_embedded_script() out_stack.size == 0
07:47:45.189974 VERBOSE [system] 0x700007887000 witness::verify() called extract_embedded_script() and returned false
07:47:45.190019 DEBUG [blockchain] Verify failed [872730] : invalid witness
```

in v4 we have no witness field, which appears to be bip141 protocol correct for this txin, whereas in v3 we somehow do have a witness and it is pushed onto the stack and verifies successfully.

**Comment by evoskuil** [comment]
When you say “we have no witness field” and “we somehow do have a witness”, are you referring to the tx as it is deserialized from the P2P connection?

If so then this has nothing to do with validation but instead is related to P2P behavior. Segwit blocks and txs are only serialized with witness data if the nodes signal segwit support via service flags. In libbitcoin is configurable. If you have segwit validation enabled but are not signaling support for it you will get non-segwit object’s from peers and will may to validate them. A soft fork makes something that what was formerly valid into invalid.

**Comment by JasonCoombs** [comment]
> When you say “we have no witness field” and “we somehow do have a witness”, are you referring to the tx as it is deserialized from the P2P connection?

I didn't see your questions until now. Here's what the problem was:

https://github.com/libbitcoin/libbitcoin-node/pull/387

with debugging process and analysis explained here:

https://github.com/libbitcoin/libbitcoin-node/issues/383

The new v4 code was not requesting witness data from the peer, so we had no witness data in the witness field (observed at runtime with debug output) and when comparing to v3 with similar debug outputs it was clear that the witness data was present as expected. This led to finding the lines of code that needed to be migrated from v3 into the new v4 code structure, as seen here:

https://github.com/libbitcoin/libbitcoin-node/pull/387/files
