### ISSUE TITLE
Channel lifetime expired early, not following channel_expiration_minutes

### ISSUE THREAD

**Issue by JasonCoombs** [libbitcoin/libbitcoin-node#423]
Any idea why my channel lifetime, which is set to the v4 default of 1440 minutes, here:

```
# The age limit for any connection, defaults to 1440.
channel_expiration_minutes = 1440
```

appears to timeout after less than 14 hours?

```
07:45:21.550312 DEBUG [node] ================= startup Tue Aug 27 21:45:21 2019 ==================
...
07:45:23.764294 INFO [network] Starting outbound session.
07:45:23.764371 VERBOSE [network] Connecting to [167.86.85.80:8333]
07:45:23.764498 INFO [node] Node is started.
07:45:24.054526 DEBUG [network] Connected to [167.86.85.80:8333]
...
21:07:54.868060 DEBUG [network] Channel lifetime expired [167.86.85.80:8333]
```

**Comment by evoskuil** [comment]
Timeouts have a randomness incorporated so that not all peers timeout at the same time.

**Comment by JasonCoombs** [comment]
Where is that in the code, please? Do you think maybe 10% variation from the configured timeout would be better?

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-network/blob/master/src/channel.cpp#L43
The timeouts are random - the configured values are maximums.

**Comment by JasonCoombs** [comment]
Thanks. Developer documentation some day would be awesome for anyone who wants to contribute to or build something new from libbitcoin.

**Comment by evoskuil** [comment]
Documentation contributions are always welcome. It’s not really the nature of open source to ask other people to do stuff. We are all volunteers, if you think it can be improved with more documentation then you are welcome to create some. Several people, including myself, have dedicated a significant amount of time on documentation (see bx wiki for example). I personally consider it a priority, given limited resources and the objectives of the project, to make the code as self-documenting as possible, to facilitate use by experienced developers and documenters.

**Comment by JasonCoombs** [comment]
You mean this, right?

https://github.com/libbitcoin/libbitcoin-explorer/wiki/Design-Overview

**Comment by JasonCoombs** [comment]
I'm not asking you to do stuff. Somebody who has spent years working with the code and knows every detail about it, such as the fact that timeouts are random by design, should some day write a document only meant for developers where the design rationale, decisions and architecture, with detailed sections on Proactor and Strands and the decision not to allow any Bitcoin protocol command to retain any state information or share any state with any other commands can be clearly articulated with citations to lines of code which implement these design decisions.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-explorer/wiki

**Comment by evoskuil** [comment]
There are thousands of things you might find interesting about the code, writing comments that are redundant with the code is counterproductive. You started with wire analysis, which led you to make assumptions, which you held to despite my cautions and explanations. I recommend reading the code.
