### ISSUE TITLE
Hardcoded height causes perf drop at block 337,459.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-node#44]
This is a `libbitcoin-blockchain` issue, see: https://github.com/libbitcoin/libbitcoin-blockchain/issues/81

**Comment by thecodefactory** [comment]
We can test by updating to a later checkpoint, no?

**Comment by evoskuil** [comment]
That's been done but this also needs to be pulled out to config. It's important that the last checkpoint and the validation switch coincide, so config needs both the height and hash of the checkpoint. But for now at least we know the cause of the huge perf difference.

**Comment by evoskuil** [comment]
Move the height/hash of the last checkpoint to config.

**Comment by evoskuil** [comment]
Implemented.
