### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by Qinli2039** [libbitcoin/libbitcoin-node#519]
I am a fan of Bitcoin, I believe that to maintain the robustness of the Bitcoin network, independent full-node clients of different software are especially important. Imagine how horrible it would be if all the nodes of Bitcoin used the same software, the same version. Can Bitcoin still talk about decentralization?and I think The security of the Bitcoin network will be greatly reduced.I noticed that libbitcoin, a standalone full-node client for Bitcoin, now has only one node running.It would be sad if one day this only node disappeared. I have a cloud server that runs bitcoin full node all year round, running bitcoin core software now, and would like to switch to "libbitcoin". My cloud server is Windows operating system. I downloaded the related software for libbitcoin, but it does not work, prompting me to initialize it first. I still can't run this client after a lot of effort,Is anyone willing to help me? Can you provide the detailed installation procedure (for windows)? My computer skills are very low, I hope someone can help, that would be very grateful！

**Comment by pmienk** [comment]
In order to help further, it would be useful to see the output of execution on the command line. Are you executing a compiled binary or claiming an issue with compilation itself?

**Comment by Qinli2039** [comment]
I just downloaded "bs-windows-x64.exe", but it  can not run normally,

**Comment by pmienk** [comment]
Did your output end with the following?

```
18:25:00.504071 ERROR [server] The "blockchain" directory is not initialized, run: bs --initchain
```

If so, I would recommend you execute the binary with the argument `--initchain` as the output assumes a binary named `bs`. If this is not what you are seeing and does not resolve your problem, please provide the output of executing the binary for further assistance.

**Comment by Qinli2039** [comment]
Hello, thank you very much for your help. I seem to be running successfully

Phillip Mienk ***@***.***> 于2023年7月6日周四 22:28写道：

**Comment by Qinli2039** [comment]
My friend is very grateful for your help, I finally run successfully. In
just half an hour, I think we've synchronized 200,000 blocks. I think it's
much more efficient than bitcoin core. I plan to run this full node on this
cloud server all year round. Can I ask you one more question? How to stop?
Can we just close the window? Or is it closed by a specific command?

qin li ***@***.***> 于2023年7月6日周四 23:23写道：

**Comment by pmienk** [comment]
The first 200,000 blocks are mostly empty and so with nearly nothing to validate you haven't really started to tax your CPU, though I'm glad you're having a good experience. You'll want to gracefully terminate the process via SIGINT (think `ctrl-c`), as SIGKILL (which is likely what will happen if you close the process or attempt to end it via task manager) will likely leave your database in an unrecoverable state, requiring a re-sync.

**Comment by Qinli2039** [comment]
Hello:
      thank you very much,in more consultation with you a question, can the
server set the pruning mode? If it can, how to set it? I want to modify the
service port 8333, how to set it? If it is convenient for you, please let
me know, thank you!

Phillip Mienk ***@***.***> 于2023年7月7日周五 04:49写道：

**Comment by pmienk** [comment]
@Qinli2039 You may wish to explore the documentation [here](https://github.com/libbitcoin/libbitcoin-server/wiki/Configuration-Settings) or see your generated `bs.cfg` file for the available settings. This issue is becoming a catch all and has been closed. If you have a specific issue, please open another or for more of this type of discussion you may want to see our [slack](https://libbitcoin.slack.com).
