### ISSUE TITLE
link error with boost lib 1.77

### ISSUE THREAD

**Issue by davxiao** [libbitcoin/libbitcoin-node#595]
Version 3.80
Compiler: clang-18
boost-lib version: 1.77

I needed to use boost v 1.77 because there is a cross-link device bug causing core dump that was fixed in 1.77

When I switched over to boost 1.77, the linker complained as below. For boost 1.76 it works. Any pointer?

```
  CXXLD    src/libbitcoin-node.la
  CXXLD    console/bn
/usr/bin/ld: /home/david/bin/lib/libbitcoin-system.so: undefined reference to `boost::filesystem::path::extension() const'
/usr/bin/ld: /home/david/bin/lib/libbitcoin-system.so: undefined reference to `boost::filesystem::path::filename() const'
/usr/bin/ld: /home/david/bin/lib/libbitcoin-system.so: undefined reference to `boost::filesystem::path::parent_path() const'
/usr/bin/ld: /home/david/bin/lib/libbitcoin-system.so: undefined reference to `boost::filesystem::path::stem() const'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:1077: console/bn] Error 1
```

**Comment by evoskuil** [comment]
It’s not clear why those symbols would not be resolved. Are they removed in 1.77 or is the component missing?

**Comment by davxiao** [comment]
Just checked boost 1.77 source code, these are there - not removed. 
where to check if the component is missing? need some guidance.

**Comment by evoskuil** [comment]
You might need to specify the component during install, though I thought file system was part of the base headers lib. @pmienk ?

**Comment by davxiao** [comment]
I think I figured out - somehow the build script got confused because I have 2 two boost versions in the lib both built by --build-boost option. 
When I cleaned up that this error is fixed - there are other problems but I will open a new ticket and closing this one.
