### ISSUE TITLE
compile error with boost 1.77 

### ISSUE THREAD

**Issue by davxiao** [libbitcoin/libbitcoin-node#596]
Version: 3.80
cc: gcc

I needed boost 1.77 because it fixed a cross device link bug that's causing bn to crash with prior boost version (1.72-1.76)

There is a compile error with 1.77. Any suggestions?

```
In file included from ./include/bitcoin/system/utility/flush_lock.hpp:25,
                 from src/utility/flush_lock.cpp:19:
./include/bitcoin/system/unicode/file_lock.hpp:22:10: fatal error: boost/interprocess/detail/posix_time_types_wrk.hpp: No such file or directory
   22 | #include <boost/interprocess/detail/posix_time_types_wrk.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:3953: src/utility/libbitcoin_system_la-flush_lock.lo] Error 1
```

**Comment by evoskuil** [comment]
It's not clear how your boost build can be missing this include, but that appears to be the case.

**Comment by pmienk** [comment]
It should be noted that the readme specifically states that the version3 branch requires Boost between 1.72 and 1.76. While this is not the error I would expect to see, there are errors expected at compile.

**Comment by evoskuil** [comment]
Min boost is now 1.78.
