### ISSUE TITLE
OSX compile break on initializer_list references [master]

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-node#69]
This issue was first published under the libbitcoin-server package as a build issue at https://github.com/libbitcoin/libbitcoin-server/issues/136.  

First want to make an assertion about the state of build environment at this end. 

Using OSX Yosemite 10.10.10

```
% uname -a
Darwin bozo 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```
```
% clang++ --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
Xcode Version 7.1.1 is installed. Which is consistent with https://gist.github.com/yamaya/2924292.

```
xcode-select --version
xcode-select version 2339.
```

Had to make the following change to get src/responder.cpp to compile.

```
% git show
commit 43133ed67b61e36cd1b305a2e31e5ca9dfb15b91
Author: skaht <sholben@bellsouth.net <mailto:sholben@bellsouth.net>>
Date:   Thu Nov 12 11:30:48 2015 -0500

   Changed the way 'const not_found lost' was initialized

diff --git a/src/responder.cpp b/src/responder.cpp
index 0a501ec..61b23b3 100644
--- a/src/responder.cpp
+++ b/src/responder.cpp
@@ -290,7 +290,7 @@ void responder::send_inventory_not_found(inventory_type_id type_id,
        hash
    };

-    const not_found lost{ { block_inventory } };
+    const not_found lost( { block_inventory } );
    node->send(lost, handler);
}
```

**Comment by evoskuil** [comment]
Please try building with the [libbitcoin/initializer branch](https://github.com/libbitcoin/libbitcoin/tree/initializer). I've modified the constructors that take [initializer_list](https://github.com/libbitcoin/libbitcoin/blob/initializer/include/bitcoin/bitcoin/message/not_found.hpp#L43).

**Comment by skaht** [comment]
https://github.com/libbitcoin/libbitcoin/blob/initializer/include/bitcoin/bitcoin/message/not_found.hpp#L43 did not fix the issue.  Still had to apply the hack up top.

**Comment by skaht** [comment]
Ignore the previous comment. Noticed that my latest download of libbitcoin didn't have the L43 change. In the process of mannually adding it.

**Comment by skaht** [comment]
Built from * (HEAD detached at c33c2fb) **c33c2fb** Use const& for std::initializer_list parameters - used nonstandard build scripts.

Build still failing at:
```
config.status: executing libtool commands
  CXX      src/src_libbitcoin_node_la-indexer.lo
  CXX      src/src_libbitcoin_node_la-full_node.lo
  CXX      src/src_libbitcoin_node_la-poller.lo
  CXX      src/src_libbitcoin_node_la-session.lo
  CXX      src/src_libbitcoin_node_la-responder.lo
  CXX      console/console_bn-dispatch.o
  CXX      console/console_bn-main.o
../libbitcoin-node/src/responder.cpp:293:29: error: no viable conversion from 'const libbitcoin::message::inventory_vector' to 'libbitcoin::message::inventory_type_id'
    const not_found lost{ { block_inventory } };
                            ^~~~~~~~~~~~~~~
1 error generated.

```

**Comment by evoskuil** [comment]
Try removing one set of braces...
```cpp
const not_found lost{ block_inventory }
```

**Comment by skaht** [comment]
Removing the set of braces as you suggest seems to work. However, the build for libbitcoin sometimes hangs when building the test scripts.

**Comment by evoskuil** [comment]
The network tests aren't unit tests, they hit testnet. I need to disable them. If you wait they should complete, though some may time out.

**Comment by evoskuil** [comment]
The second set of braces was incorrect in that context.

**Comment by skaht** [comment]
Completed a build using libbitcoin commit da71f4c1a1673b13cf60d425f6b9386ba849f7ae today.  Still needing to remove the inner braces from file src/responder.cpp to get libbitcoin-node commit cfa23214906172df9bb5f569b0352f1582ea1005 to compile.

**Comment by skaht** [comment]
This bug still remains on OSX for a master build.  

Also noticed that setting the following environmental variables to be necessary for configures for both bs & bx to complete:

setenv SED        $HOMEBREW_LIBRARY_PATH/ENV/4.3/sed
setenv LIBTOOL $HOMEBREW_PREFIX/opt/libtool/bin/glibtool

FYSA - https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/External-Commands.md#shell-scripts provides details for setting HOMEBREW_LIBRARY_PATH and HOMEBREW_PREFIX.  Been installing homebrew packages in non-standard locations for over 18 months very successfully to minimize escalation of privileges for installations.

**Comment by evoskuil** [comment]
I haven't had a need to set either of these to build bs or bx using Homebrew dependencies, but I use the default Homebrew installation.

**Comment by evoskuil** [comment]
Fixed in https://github.com/libbitcoin/libbitcoin-node/commit/b911471fc52a029eb3ab6cc764fabe76dbd95104
